#!/usr/bin/env ruby -W0
# frozen_string_literal: true

# vim: ft=ruby

require 'octokit'
require 'colored2'
require 'dry/cli'

lib_path = File.expand_path("../lib", __dir__)
$LOAD_PATH << lib_path if File.exist?(lib_path)

require 'githuh'

Githuh::CLI::Launcher.new(ARGV.dup).execute!
